### ISSUE TITLE
Add Credits for my work 

### ISSUE THREAD

**Issue by Thordekk** [ProjectNighthold/NightholdCore#1]
Scripts for undead is full maded by me, where i appear on credits and who autorize to put my code?

**Comment by LordArcanine** [comment]
Adding credit to someone that stole the work of others and sell it like is his property?
You have the nerve to steal code from others without remorse, sadly i have proof of that.

Trinitycore, the base for the uwow leak, the emu that you copied work from other devs to say is your emu, is under GPL Licence.

As everybody knows GNU or GPL licence says that if you do code in base of a code already with that licence atached, you must share it adding the correct thanks to the devs involved in the code.

When you sold it to me, he code had no history of changes, only some changes from 2 of your devs, so I will not be able to know how many contributors really participated in it. And in this way, I wont be able to mention and thank them for the work that each one of them did.

I didnt add you in the thanks file because you stole 99% of the code from others, otherwise in any part of the emu there are a line of credits that mentions you in any way.

The undead script was copied from other place, remember i was seeing your screen when you get that code from other place and edited (still not functional by the way i need to remake it) the good thing is my Partner Stevej (@pangolp) is working on a better worked script.

Sadly i dont have all the names of the devs that are in your team that contributed, they deserve full credit because they didnt steal code like you,  only worked on something that his/her team was working. 

Closed, i will add you to the thanks file but you will not like it.

**Comment by Thordekk** [comment]
hhhHAHHAHHA buena suerte veremos cuanto duran tus proyectos :)

**Comment by pangolp** [comment]
> hhhHAHHAHHA buena suerte veremos cuanto duran tus proyectos :)

Estas invitado a participar si queres, dado que es un proyecto open source.
Cualquier cosa, ya sabes donde encontrarnos y gracias por la buena suerte, la vamos a necesitar.
Mas en una comunidad, donde nadie comparte nada, se quedan el trabajo de otras personas...
